### ISSUE TITLE
after clean install on smartosvm - node is unwritable db directory + some warnings

### ISSUE THREAD

**Issue by lundakj** [wachunga/omega#21]
Hi,
1. after clean install on smartos zone (git-node method) is unwritable db directory. 
2. some warnings in log:

- connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
- connect deprecated limit: Restrict request size at location of read at node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
- connect deprecated methodOverride: use method-override npm module instead at server/app.js:71:17

I know, old project. But nice, so I use, I report :)

**Comment by wachunga** [comment]
Thanks for the report. Just merged a PR to upgrade to express 4, which should clean up the warnings (2). As for (1), I'm not familiar with smartos zone but maybe you can redis instead (`--redis`)?
